Feat:Added GetValues and Patchwork
DendraScience/dendra-wof-web-service pull request #15
Opened 2022-10-27 00:20 UTC by ergjustin

Added GetValues and Patch works

2022-10-28 01:16 UTC, jscottsf requested changes
A few items.

Also, I thought the uniquing in `GetSiteInfo/Object` was to be removed. Hence no need for `uniqueVariables`.  This is iterating over each series (datastream) and hence we need each series to be represented, not uniqued by variable.

2022-10-28 01:16 UTC, jscottsf commented on src/lib/helpers.js
>      },
Insert blank line after.

2022-10-28 01:16 UTC, jscottsf commented on src/lib/helpers.js
> +    dateformater(dt) {
dateformater mispelled. `dateFormatter`.

Suggestion, rename to `toTime`. It doesn't actually format a date object, but it casts from a string to a time integer.

Actually prefer `str` since the input is a string. `dt` tends to tell me that the input is a date type.

Also, remove parsing the date twice (extra cycles).

```
    toTime(str) {
      if (!str) return
      const time = new Date(str.endsWith('Z') ? str : str + 'Z').getTime()
      if (!isNaN(time)) return time
    }
```

2022-10-28 01:16 UTC, jscottsf commented on src/soap/handlers/GetSiteInfoObject.js
> +        const datapointsParams = Object.assign({
`Object.assign` not needed here.

Just combine into a single statement.

```
        const datapoints = await helpers.findMany('datapoints', {
          datastream_id: datastream._id,
          fn: 'count'
        })
```

2022-10-28 01:16 UTC, jscottsf commented on src/soap/handlers/GetSiteInfoObject.js
> +        const valCount = datapoints && datapoints.length && datapoints[0].v
You need to reduce over the datapoints to get a total since more than one count can be returned due to multiple config slices being processed. Renamed to `vCount` since it's a count composed from the `v` attribute.

```
       const vCount =
          datapoints &&
          datapoints.reduce((total, datapoint) => {
            return total + datapoint.v
          }, 0)
```

2022-10-28 01:16 UTC, jscottsf commented on src/soap/handlers/GetValuesObject.js
> +  // Check for Invalid Date
Refactor:

```
  const startTime = helpers.toTime(startDate)
  const endTime = helpers.toTime(endDate)

  // Check for invalid date parameters
  if (startDate && !startTime)
    throw new Error(`Invalid startDate parameter '${startDate}'`)
  if (endDate && !endTime)
    throw new Error(`Invalid endDate parameter '${endDate}'`)
```

2022-10-28 01:16 UTC, jscottsf commented on src/soap/handlers/GetValuesObject.js
>              methodId,
Should be `methodID`.

2022-10-28 01:16 UTC, jscottsf commented on src/soap/serializers/value.js
>    const dateTime = new Date(datapoint.lt).toISOString().replace('.000Z', '')
Can we refactor both of these to use `substring` to trim? Faster than a replace especially when we are calling so many times.

2022-10-28 01:16 UTC, jscottsf commented on src/soap/serializers/value.js
> +  const toFixed = utcTimeOffset !== undefined && utcTimeOffset.toFixed(2)
Logic error. Example: A UTCOffset of `-5.5` should be `-05:30`.

2022-10-28 01:16 UTC, jscottsf commented on src/soap/serializers/value.js
> +  const twoDigitNumber = n => {
I would just create and export a serializer called `timeOffset` at the top of the file that takes a number `offset` and serializes it to the formatted string. Basically combine the logic of twoDigitNumber with the other logic. Keeps it all in one place and can be reused (or have a separate test case some day if we desire).

2022-10-28 19:37 UTC, jscottsf requested changes

2022-10-28 19:37 UTC, jscottsf commented on src/soap/handlers/GetValues.js
> +  const methodIds = new Map()
Should be `methodIDs` and `methodID`. Same as others.

2022-10-28 20:18 UTC, ergjustin commented on src/soap/handlers/GetValues.js
> +  const methodIds = new Map()
Done with the update, I forgot it yesterday.

2022-10-29 01:21 UTC, jscottsf approved these changes

2022-10-29 01:22 UTC, merged